In [1]:
import numpy as np

What is Vectorization?
Vectorization means replacing slow python loops with fast numpy operations.

In [ ]:
#slow loop
a = [1, 2, 3, 4]
b = [2*x for x in a]

[2, 4, 6, 8]

In [4]:
#fast(vectorized)
a = np.array([1, 2, 3, 4])
b = 2*a
b

array([2, 4, 6, 8])

What is Broadcasting?
Broadcasting allows numpy to perform operations between arrays of different shapes.
it stretches smaller arrays to match the shape

In [5]:
#1. Add scalar to array
a = np.array([1, 2, 3])
a + 10 #10 is broadcasted to [10, 10, 10]

array([11, 12, 13])

In [18]:
#add 2d + 1d
a = np.array([[1, 2, 3], [4,5,6]])
b = np.array([10, 20, 30])
a + b




array([[11, 22, 33],
       [14, 25, 36]])