In [ ]:
import numpy as np

1. VIEW VS COPY

view:
    *No new data is created
    *just another window into the same data in memory
    *changes in the view affects the original array

In [ ]:
a = np.arange(1, 4)
print(a)
v = a[1:]
v[0] = 7
print(v) #the view
print(a) #the original array

copy:
    *New data is copied.
    *no effect in the original array.

In [ ]:
a = np.arange(1, 4)
print(a)
c = a[:].copy()
c[0] = 99
print(c)
print(a)

2. memory layout

In [ ]:
a = np.array([[1, 2], [3, 4]], order='C')
b = np.array([[1, 2], [3, 4]], order='F')
print(a.flags)
print(b.flags)

3. ravel() vs flatten()
function    copy    editable
flatten()   yes     no
ravel()     no      yes

In [11]:
a = np.array([[1, 2], [3, 4]])
f = a.flatten()
r = a.ravel()
print(f)
print(a)
r[0] = 10
print(r)

[1 2 3 4]
[[1 2]
 [3 4]]
[10  2  3  4]
