In [2]:
import numpy as np

In [3]:
a = np.arange(1, 10).reshape(3, 3)
a #want to test

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b = np.zeros(10, dtype='int')
print(b)
b[5] = 1
b


[0 0 0 0 0 0 0 0 0 0]


array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [5]:
c = np.arange(16).reshape(4, 4)
c.fill(7)
c


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [6]:
d = np.arange(1, 10).reshape(3, 3)
print(d)
d[:, -1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 6, 9])

In [7]:
e = np.arange(10, 51, 10)
print(e)
e[::-1]

[10 20 30 40 50]


array([50, 40, 30, 20, 10])

In [8]:
f = np.ones(9, dtype='int').reshape(3, 3)
f[1, 1] = 9
f


array([[1, 1, 1],
       [1, 9, 1],
       [1, 1, 1]])

In [11]:
g = np.array([1, 2, 3, 4])
np.save('test1.npy', g)
load = np.load('test1.npy')
print(load)

[1 2 3 4]


In [17]:
h = np.arange(1, 10).reshape(3, 3)
np.savetxt('test2.txt', h, delimiter=',', fmt='%d')
load = np.loadtxt('test2.txt', delimiter=',', dtype='int')
print(load)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
i = np.arange(12).reshape(3, 4)
i

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
j = np.arange(1, 10).reshape(3, 3)
print(j)
k = j.flatten()
print(k, k.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9] 1


In [35]:
l = np.zeros((2, 2))
m = np.ones((2, 2))
print(np.vstack((l, m)))
print(np.hstack((l ,m)))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [46]:
n = np.array([[1], [2], [3]])
o = np.array([10, 20, 30])
print(n+o)
result = ((n*2)-2), ((o*2)-2)
result

[[11 21 31]
 [12 22 32]
 [13 23 33]]


(array([[0],
        [2],
        [4]]),
 array([18, 38, 58]))

In [51]:
p = np.arange(1, 5)
q = np.arange(5, 9)
print(p, q)
print(p+1, q+1)
print(p-1, q-1)
print(p*2, q*2)
print(p/2, q/2)

[1 2 3 4] [5 6 7 8]
[2 3 4 5] [6 7 8 9]
[0 1 2 3] [4 5 6 7]
[2 4 6 8] [10 12 14 16]
[0.5 1.  1.5 2. ] [2.5 3.  3.5 4. ]


In [58]:
r = np.array([1, 4, 9, 16, 25])
print("root: ",np.sqrt(r),"log: ",np.log(r),"square: ",np.square(r))

root:  [1. 2. 3. 4. 5.] log:  [0.         1.38629436 2.19722458 2.77258872 3.21887582] square:  [  1  16  81 256 625]


In [63]:
s = np.arange(1, 10).reshape(3, 3)
print(s)
print(np.sum(s))
print("max: ",np.max(s),"min: ",np.min(s),"mean: ",np.mean(s),"std: ",np.std(s))
print(np.sum(s, axis=0)) #column
print(np.sum(s, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
max:  9 min:  1 mean:  5.0 std:  2.581988897471611
[12 15 18]
[ 6 15 24]


In [73]:
t = np.random.randint(1, 101, size=(4,4)) #generates an array of random integers
t


array([[85, 75, 49,  8],
       [18, 99, 76, 57],
       [54, 18, 70, 98],
       [18, 25, 64, 43]], dtype=int32)

In [83]:
u = np.random.rand(2, 5)
u


array([[0.22106799, 0.37309558, 0.82611677, 0.56087356, 0.78257735],
       [0.48634901, 0.49288439, 0.37105605, 0.27746287, 0.10940358]])