In [ ]:
import numpy as np

TASK-1

In [ ]:
a = np.arange(1,25)
print(a.size)
print(a.reshape(4, 3, 2))
a.flatten()


TASK 2

In [ ]:
b = np.arange(1, 16).reshape(3, 1, 5)
print(b)
c = np.squeeze(b)
print(c)
c.ndim


TASK 3

In [23]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
c = np.vstack((a, b))
print(c)
d = np.hstack((a, b))
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


TASK-4

In [ ]:
a = np.arange(1, 11)
print(a)
np.split(a, 5, axis=0)

[ 1  2  3  4  5  6  7  8  9 10]


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]