In [ ]:
import numpy as np

1. Elemental-Wise Arithmetic

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

In [ ]:
a = np.array([1, 2, 3])
print(a+5)
print(a*10)
print(a**2)

In [ ]:
b = np.array([1, 2, 3])
print(np.sqrt(b))
print(np.exp(b))
print(np.sin(b))

4. Aggregate Functions

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))


5. comparison and logical  ops

In [ ]:
a = np.array([1,2,3,4])
print(a>2)
np.logical_and(a>1, a<4)

6. Broadcasting(!Very Important):- Broadcasting lets numpy apply operations to 
arrays of different shapes...

In [ ]:
a = np.array([1, 2, 3])
b = 2
print(a+b)

#2D example
arr = np.array([[1,2,3], [4,5,6]])
vec = np.array([1,0,1])
print(arr+vec) #dimensions must be equal or one of them must be 1..

[3 4 5]
[[2 2 4]
 [5 5 7]]
