Numpy arrays can be defined using python lists and tuples.
1.a list of numbers will create a 1D array,

2.a list of lists will create a 2D array,

3.further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.

In [ ]:
import numpy as np
a1 = np.array([1, 2, 3, 4])
a2 = np.array([[1,2],[3,4]])
a3 = np.array([[[1,2],[3,4],[5,6],[7,8]]])


1- 1D ARRAY CREATION
The 1D array creation functions e.g. numpy.linspace and numpy.arange

In [ ]:
print(np.arange(10))
print(np.arange(2, 10, dtype=float))
print(np.arange(2, 3, 0.1))

In [ ]:
print(np.linspace(1., 5., 6))

2- 2D ARRAY CREATION
The 2D array creation functions e.g. numpy.eye, numpy.diag, and numpy.vander

In [ ]:
print(np.eye(3))
print(np.eye(3, 5))

In [ ]:
print(np.diag([1, 2, 3]))
print(np.diag([1,2,3], 1))

3 - GENERAL ndarray creation functions
The ndarray creation functions e.g. numpy.ones, numpy.zeros, and random define arrays based upon the desired shape. 

In [ ]:
print(np.zeros((2,3)))
np.zeros((2, 3, 2))

In [ ]:
np.ones((2, 3))
np.ones((2, 2, 3))

In [ ]:
np.random.randn(1, 10)

3) replicating, joining or mutating existing arrays.


In [ ]:
#about view
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a=', a, 'b=', b) #the orginial copy is also changed.

a= [2 3 3 4 5 6] b= [2 3]


In [ ]:
#copy
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b) #A copy

a =  [1 2 3 4] b =  [2 3]


There are a number of routines to join existing arrays e.g. numpy.vstack, numpy.hstack, and numpy.block..

In [21]:
a = np.ones((2,2))
print(a)
b = np.eye(2,2)
print(b)
c = np.zeros((2,2))
print(c)
d = np.diag((-3, -4))
print(d)
np.block([[a, b], [c, d]])


[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[-3  0]
 [ 0 -4]]


array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])