In [ ]:
import numpy as np

vector = A 1D Array
matrix = A 2D Array
tensor = An N-Dimensional array

1. Matrix Creation in Numpy

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a, b #a, b are 2x2 matrices

2. Matrix Transpose--> swap rows and columns

In [ ]:
a.T
#or
np.transpose(a)

3. Matrix Multiplication--> each row of A multiply with each column of B

In [ ]:
a@b

4. Identity matrix--> np.eye()

In [ ]:
i = np.eye(3)
i

5. Inverse of a matrix--> np.linalg.inv()

In [ ]:
b = np.array([[5, 6], [7, 8]])
inv = np.linalg.inv(b)
inv

Determinant--> np.linalg.det()

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))
b = np.array([[5, 6], [7, 8]])
round = np.round(np.linalg.det(b), 2)
round

7. Rank of matrix--> np.linalg.matrix_rank()

In [ ]:
np.linalg.matrix_rank(b)

8. solving linear equations--> np.linalg.solve()

In [ ]:
x = np.linalg.solve(a, b)
x

practice

In [ ]:
#1.
a = np.arange(1, 7).reshape(2, 3)
print(a)
print(np.transpose(a))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [40]:
#2.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a@b

array([[19, 22],
       [43, 50]])

In [ ]:
#3.
c = np.eye(3)
d = np.arange(1, 10).reshape(3,3)
print(c@d)
print(d)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
#4.
e = np.array([[4, 7], [2, 6]])
inv = np.linalg.inv(e)
print(inv)
identity =  np.dot(e, inv)
print(identity)

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [54]:
a = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])
x = np.linalg.solve(a, b)
x

array([1., 2.])

In [ ]:
d =  np.array([[2, 4], [1, 2]])
print(np.linalg.matrix_rank(d))
print(np.linalg.det(d))


1
0.0
