In [1]:
import numpy as np

1. np.unique()

In [2]:
a = np.array([1, 2, 2, 3, 4, 5, 6, 6])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

common elements--> np.intersect1d()

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
np.intersect1d(a, b)

array([3, 4])

3. np.setdiff1d()

In [4]:
np.setdiff1d(a, b)

array([1, 2])

4. Exclusive to a or b

In [5]:
np.setxor1d(a, b)

array([1, 2, 5, 6])

5. All unique elements

In [6]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

6. Element Wise Membership test

In [9]:
print(np.isin(a, b)) #np.in1d
a[np.isin(a, b)]

[False False  True  True]


array([3, 4])