In [1]:
import numpy as np

Build a mini system to simulate and analyze, student marks

In [2]:
#step-1: Generate Random data
np.random.seed(0)

#50 students, 5 subjects
marks = np.random.randint(35, 100, size=(50, 5))
print("Marks (first 5 students):\n", marks[:5])

Marks (first 5 students):
 [[79 82 99 44 56]
 [71 47 93 74 81]
 [72 60 44 55 82]
 [99 84 64 54 54]
 [49 74 67 44 92]]


In [3]:
#step 2: calculate stats
#1. Mean marks per student
student_avg = np.mean(marks, axis=1)

#2. Mean marks per subject
subject_avg = np.mean(marks, axis=0)

#3. student with highest avg
top_student = np.argmax(student_avg)
 
#4. pass/fail status
pass_status = np.all(marks>= 40, axis=1)


In [4]:
#step 3: output
print("Average marks per subject:", subject_avg)
print("Top student index:", top_student)
print("number of students who passed all subjects:", np.sum(pass_status))

Average marks per subject: [66.86 69.18 68.8  59.6  66.04]
Top student index: 46
number of students who passed all subjects: 27
